version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "deps:"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    commit-message:
      prefix: "deps:"
    open-pull-requests-limit: 10
