name: Lint Code

on:
  push:
    branches:
      - 'feature/**'
      - develop
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: |
          frontend/yarn.lock
          backend/yarn.lock
    
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: yarn install
    
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: yarn install
    
    - name: Lint Frontend
      working-directory: ./frontend
      run: yarn lint
    
    - name: Lint Backend
      working-directory: ./backend
      run: yarn lint
    
    - name: Check Code Formatting
      run: npx prettier --check .