name: Code Style Check

on:
  push:
    branches:
      - 'feature/**'
      - develop
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Prettier
      run: npm install -g prettier

    - name: Check Code Formatting
      run: |
        prettier --check .github/dependabot.yml \
          .github/ISSUE_TEMPLATE/*.md \
          .github/PULL_REQUEST_TEMPLATE/*.md \
          .github/workflows/lint.yml \
          compose.yml \
          README.md

    - name: Auto-format if neededF
      run: |
        prettier --write .github/dependabot.yml \
          .github/ISSUE_TEMPLATE/*.md \
          .github/PULL_REQUEST_TEMPLATE/*.md \
          .github/workflows/lint.yml \
          compose.yml \
          README.md

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Style: Auto-format files with Prettier" || exit 0
        git push